import type { RevisionDirectiveKind } from "./evaluation.js";

export type ModelRole =
    | "planner"
    | "structure"
    | "orchestrator"
    | "audio_renderer"
    | "structure_evaluator"
    | "audio_evaluator"
    | "summary_evaluator";

export interface LearnedSamplingParams {
    temperature?: number;
    topP?: number;
    topK?: number;
    seedOffset?: number;
}

export interface LocalizedRewriteDirectiveHint {
    sectionId: string;
    kind: RevisionDirectiveKind;
    reason: string;
}

/** Specification for a NotaGen localized section rewrite request. */
export interface LocalizedRewriteSpec {
    /** Section IDs that should be regenerated by NotaGen. */
    rewriteSectionIds: string[];
    /** Section IDs that should be preserved byte/event-stable from the prior candidate. */
    keepSectionIds: string[];
    /** Human-readable overall reason for the rewrite (included in the prompt). */
    reason: string;
    /** Per-section directive hints forwarded to the rewrite prompt. */
    directives: LocalizedRewriteDirectiveHint[];
    /** Previous ABC text from the parent candidate (for byte-stable section assembly). Optional. */
    previousAbcText?: string;
}

export interface ModelBinding {
    role: ModelRole;
    provider: string;
    model: string;
    version?: string;
}
